name: Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      image: centos:7
    steps:
    - uses: actions/checkout@v2
    - uses: codespell-project/actions-codespell@master
      with:
        ignore_words_list: fo,wee
    - name: Install dependencies
      run: |
        curl -L -O https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-Linux-x86_64.sh
        chmod +x cmake-3.16.4-Linux-x86_64.sh
        ./cmake-3.16.4-Linux-x86_64.sh --skip-license --prefix=/usr/local
        curl -L -O https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-16.02-20.el7.x86_64.rpm
        curl -L -O https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-plugins-16.02-20.el7.x86_64.rpm
        rpm -U --quiet p7zip-16.02-20.el7.x86_64.rpm
        rpm -U --quiet p7zip-plugins-16.02-20.el7.x86_64.rpm
        yum install -y make gcc-c++ libasan clang-analyzer

    - name: Build debug ninja
      shell: bash
      env:
        CFLAGS: -fstack-protector-all -fsanitize=address
        CXXFLAGS: -fstack-protector-all -fsanitize=address
      run: |
        scan-build -o scanlogs cmake -DCMAKE_BUILD_TYPE=Debug -B debug-build
        scan-build -o scanlogs cmake --build debug-build --parallel --config Debug

    - name: Build release ninja
      shell: bash
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -B release-build
        cmake --build release-build --parallel --config Release
        strip release-build/ninja


