name: Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      image: centos:7
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
    steps:
    - uses: actions/checkout@v2
    - uses: codespell-project/actions-codespell@master
      with:
        ignore_words_list: fo,wee
    - name: Install dependencies
      run: |
        curl -L -O https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-Linux-x86_64.sh
        chmod +x cmake-3.16.4-Linux-x86_64.sh
        ./cmake-3.16.4-Linux-x86_64.sh --skip-license --prefix=/usr/local
        curl -L -O https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-16.02-20.el7.x86_64.rpm
        curl -L -O https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-plugins-16.02-20.el7.x86_64.rpm
        rpm -U --quiet p7zip-16.02-20.el7.x86_64.rpm
        rpm -U --quiet p7zip-plugins-16.02-20.el7.x86_64.rpm
        yum install -y make gcc-c++ libasan clang-analyzer
        
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        # queries: ./path/to/local/query, your-org/your-repo/queries@main
        queries: +security-and-quality@main

    - name: Build debug ninja
      shell: bash
      env:
        CFLAGS: -fstack-protector-all -fsanitize=address
        CXXFLAGS: -fstack-protector-all -fsanitize=address
      run: |
        scan-build -o scanlogs cmake -DCMAKE_BUILD_TYPE=Debug -B debug-build
        scan-build -o scanlogs cmake --build debug-build --parallel --config Debug

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

